spring:
  application:
    name: admin-service

  datasource:
    url: ${DB_USER_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    repair-on-migrate: true
    table: flyway_schema_history_admin

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

