spring:
  application:
    name: budget-service

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

