spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
      routes:
        - id: user-service-route
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: admin-user-route
          uri: http://user-service:8081
          predicates:
            - Path=/api/admin/**
        - id: transaction-service-route
          uri: http://transaction-service:8083
          predicates:
            - Path=/api/transactions/**
        - id: ingestion-service-route
          uri: http://ingestion-service:8082
          predicates:
            - Path=/api/ingestion/**
        - id: budget-service-route
          uri: http://budget-service:8084
          predicates:
            - Path=/api/budgets/**
        - id: notification-service-route
          uri: http://notification-service:8086
          predicates:
            - Path=/api/notifications/**
        - id: notification-ws-route
          uri: http://notification-service:8086
          predicates:
            - Path=/ws/**
        - id: chat-service-route
          uri: http://chat-service:8087
          predicates:
            - Path=/api/chat/**
        - id: forecasting-service-route
          uri: http://forecasting-service:8000
          predicates:
            - Path=/api/forecast/**

security:
  jwt:
    issuer: finsight-user-service
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArW7FXQCJeeUm/la84gPQ
      vZV91fsWbhe/URGkzjKDTV/t0H1hbYeD/tJlqJMnRcmHhi6gbJiPULj4siffH0+u
      tZd3XOS9xOa8Ujuxc1DPLWAt3wgmI/IYqPmuhalikNNsAwUR2T/9DHnFmpl/PXlT
      9aFVDsWyG0iN8Kb3F825r0wI5UGiad+OM50rCT7IjD9RTquCtM5LaeX6I2aJzIN+
      Ol92y/UmMAZFmknzeJ+37rLfQtURz+CF1HsOlQMcqAGuvHWdNpabwF/B39XlK59l
      WOAXlPyozGH10AIzWHvhiKKo9qssXDftthpjqZKD2DQNQUUDcaeYOMD6aacfdIcn
      PQIDAQAB
      -----END PUBLIC KEY-----

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
