spring:
  application:
    name: ingestion-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 22MB

security:
  jwt:
    issuer: ${JWT_ISSUER}
    public-key: ${JWT_PUBLIC_KEY}

ingestion:
  kafka:
    topic: transactions.ingested
  supported-types:
    - text/csv
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/pdf
    - application/octet-stream

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
